<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
    <title>Privacy</title>
</head>

<body>
    <!-- <?php include("navbar.php"); ?> -->
    <div class="privacy_beleid_container">
        <h2>Privacybeleid</h2><br>
        <p>In ons privacybeleid leggen we uit hoe we uw persoonlijke gegevens verzamelen en gebruiken wanneer u met ons reist, onze website bezoekt, onze mobiele app gebruikt of op een andere manier met ons communiceert. Zorg ervoor dat u het beleid zorgvuldig leest.</p><br>
        <div class="over_dit_privacy_beleid">
            <h2>Over dit privacybeleid</h2><br>
            <p>Dit privacybeleid is van toepassing op alle persoonsgegevens die CRUDAirlines verwerkt wanneer u als klant onze websites of mobiele apps gebruikt of contact met ons opneemt. Wij verwerken uw persoonsgegevens primair om uw boeking af te handelen, uw reis en aankopen te verzorgen en uw vragen te beantwoorden. Wij gebruiken uw gegevens ook om u aanbiedingen te doen die zijn afgestemd op uw interesses en voorkeuren.</p><br>
            <p>In dit privacybeleid vindt u meer informatie over de persoonsgegevens die wij verzamelen en verwerken en welke rechten u heeft. Klik hieronder op de betreffende paragraaf voor meer informatie.</p><br>
            <div class="privacybeleid_wij_zijn_wij">
                <button class="accordion">1. Wij zijn wij!</button>
                <div class="panel"><br>
                    <p>Wij zijn de Create Read Update Delete Luchtvaart Maatschappij NV (ook bekend als CRUDAirlines Royal Dutch Airlines of CRUDAirlines), gevestigd aan de Wankywankyweg 69, 6969 LO Nijmegen.</p><br>
                    <p>CRUDAirlines is onderdeel van de Air CRUD Groep. Kijk voor meer informatie op onze website onder ‘Corporate‘. CRUDAirlines is verantwoordelijk voor de verzameling en het gebruik van uw persoonsgegevens conform dit privacybeleid.</p><br>
                    <p>Wij bieden ons loyaliteitsprogramma CRUDbiz aan in samenwerking met onze groepsmaatschappij Air CRUD. Air CRUD (Société Air CRUD, S.A.) is een luchtvaartmaatschappij gevestigd aan Rue de Paris 45, F-95747, Roissy CDG Cedex, Frankrijk. Wij zijn samen verantwoordelijk voor de verwerking van uw persoonsgegevens in het kader van het loyaliteitsprogramma CRUDbiz. Een onderlinge regeling bepaalt onze wederzijdse verantwoordelijkheden voor de naleving van de toepasselijke privacywetgeving. Kort gezegd hebben wij afgesproken dat u contact kunt opnemen met het Privacy Office van ofwel CRUDAirlines ofwel Air CRUD (zie 'Uw rechten' hieronder) als u uw rechten wilt uitoefenen of als u een klacht heeft over de verwerking van uw persoonsgegevens. CRUDAirlines en Air CRUD assisteren elkaar waar nodig om te waarborgen dat u uw rechten kunt uitoefenen. En we zorgen er samen voor dat uw vragen en klachten worden afgehandeld.</p><br>
                </div>
            </div>
            <div class="privacybeleid_persoonsgegevens_verwerken">
                <button class="accordion">2. De soorten persoonsgegevens die wij verwerken</button>
                <div class="panel"><br>
                    <h2>2.1. Algemeen</h2><br>
                    <p>Wij kunnen de volgende categorieën persoonsgegevens verzamelen en verwerken:</p><br>
                    <span>(A) Naam, paspoortnummer en overige identiteitsgegevens</span>
                    <p>Als u een reservering plaatst of een vlucht bij ons boekt, registreren wij uw naam, titel, geslacht, geboortedatum, nationaliteit, woonland en paspoortgegevens. Als u een reservering plaatst of een vlucht boekt voor andere personen, registreren wij ook hun identiteitsgegevens. U dient ervoor te zorgen dat zij weten dat wij hun persoonsgegevens verzamelen en op welke wijze wij van die gegevens gebruikmaken.</p><br>
                    <span>(B) Uw contactgegevens en gegevens over uw persoonlijke account of registratie</span>
                    <p>Wij kunnen uw adres, telefoonnummer en e-mailadres verzamelen. Als u zich voor een dienst, evenement, prijsvraag of actie registreert of een persoonlijke account aanmaakt, kunnen we ook uw inloggegevens en andere informatie vastleggen die u bij het registreren of op het accountformulier invult. Reist u voor zaken, dan registreren wij ook gegevens over uw organisatie, zoals naam en adres.</p><br>
                    <span>(C) Informatie over uw reserveringen, boekingen en aankopen</span>
                    <p>Als u een reservering plaatst of een vlucht bij ons boekt, verwerken wij uw reserverings- en boekingsgegevens, zoals gegevens over uw vlucht, de prijzen en de datum van uw reservering of boeking. Daarnaast verwerken wij gegevens over de aankoop van aanvullende diensten (zoals extra bagage, upgrades, wifi aan boord) en producten.</p><br>
                    <span>(D) Informatie over uw reis</span>
                    <p>Als u met ons reist, verwerken wij informatie over uw reis zoals uw reisschema, online of op de luchthaven inchecken, mobiele of geprinte boarding pass en informatie over uw reisgenoten.</p><br>
                    <p>Ook kunnen we uw specifieke medische behoeften of dieetwensen en eventueel benodigde aanvullende hulp vastleggen. Van het externe bedrijf dat de biometrische boarding regelt (bijvoorbeeld via gezichtsherkenning), ontvangen wij normaliter een bevestiging dat uw identiteit is geverifieerd. Tenzij anders aangegeven, ontvangen wij geen andere identiteitsgegevens over u (zoals gezichtsafbeeldingen) dan de persoonsgegevens waarover wij al beschikken (zoals paspoortgegevens). Voor meer informatie over de verwerking van uw persoonsgegevens in het kader van biometrische boarding, verwijzen wij naar het privacybeleid van de organisatie die de biometrische boarding verzorgt.</p><br>
                    <p>Vóór het boarden of uitstappen, kunnen wij ook gezondheidscontroles uitvoeren of uw gezondheidsgegevens verzamelen of gebruiken omdat wij hiertoe wettelijk verplicht zijn, om redenen van algemeen belang op het gebied van de volksgezondheid, of met uw uitdrukkelijke toestemming.</p><br>
                    <span>(E) Informatie in het kader van ons zakelijke loyaliteitsprogramma</span>
                    <p>Als u deelneemt aan ons zakelijke loyaliteitsprogramma CRUDbiz, verwerken wij uw deelnemersnummer, CRUDcoins-saldo, rewards en voordelen, deelnemerssoort en -niveau en overige informatie met betrekking tot uw deelname. Ook registreren wij de transacties waarmee u CRUDcoins verdient of gebruikt. Wij registreren onder meer de soort transactie (b.v. een vlucht), de transactiedatum, de verdiende of gebruikte CRUDcoins en de aanbieder (Air CRUD, CRUDAirlines of CRUDbiz-partner).</p><br>
                    <p>We kunnen de gegevens over uw deelname aan Flying CRUD aanwenden voor het leveren of promoten van diensten aan u (zie 4.1 hierna).</p><br>
                    <span>(F) Onze communicatie met u</span>
                    <p>Als u ons een e-mail stuurt of online of via sociale media met ons chat, registreren wij uw berichten. Als u ons belt, legt onze klantenservice uw vragen of klachten vast in onze database. Ook kunnen we telefoongesprekken opnemen voor trainingsdoeleinden of ter preventie en bestrijding van fraude. Wij registreren uw communicatievoorkeuren, bijvoorbeeld wanneer u zich aan- of afmeldt voor één van onze nieuwsbrieven, of als u ervoor kiest om informatie of alerts over uw boeking te ontvangen (zoals uw boarding pass en updates over uw vluchtstatus) via andere kanalen dan e-mail (zoals WhatsApp, Messenger of WeChat).</p><br>
                    <span>(G) Informatie die wij verzamelen als u gebruikmaakt van onze websites, mobiele apps en andere digitale media</span>
                    <p>i. Wanneer u onze websites bezoekt of gebruikmaakt van onze mobiele apps of andere digitale diensten, kunnen wij uw IP-adres, type browser, besturingssysteem, doorverwijzende website, surfgedrag en appgebruik vastleggen. Deze informatie wordt verzameld via cookies en vergelijkbare technologieën. Meer informatie is te vinden in ons cookiebeleid. Als u onze websites bezoekt via een link in een e-mail of als u inlogt op uw CRUDAirlines-account of Flying CRUD-account, kunnen wij de informatie die we via cookies en vergelijkbare technologieën verzamelen, koppelen aan andere gegevens die wij al van u hebben.
                        ii. Wij ontvangen automatisch bericht wanneer u onze e-mails opent of op een link in deze e-mails klikt. Deze informatie kunnen wij koppelen aan andere gegevens die wij al van u hebben.
                        iii. Met uw toestemming kunnen wij uw locatiegegevens ontvangen.
                        iv. U kunt ons toestemming geven om toegang te verkrijgen tot bepaalde gegevens op uw mobiele telefoon, zoals foto's en contactpersonen.
                    </p><br>
                    <span>(H) Gegevens met betrekking tot sociale media</span>
                    <p>Afhankelijk van uw sociale-netwerkinstellingen kunnen wij gegevens ontvangen van uw sociale-netwerkprovider. Als u bijvoorbeeld via een social media-account inlogt op onze diensten, kunnen wij uw social media-profiel ontvangen, met uw contactgegevens, interesses en contactpersonen. Daarnaast ontvangen we bezoekersstatistieken van Facebook in verband met onze Facebook-fanpagina. CRUDAirlines is samen met Facebook verantwoordelijk voor deze bezoekersstatistieken, maar Facebook Ireland Limited is uw eerste aanspreekpunt en behandelt verzoeken tot uitoefening van uw rechten en eventuele klachten. Wij helpen Facebook zo nodig bij de behandeling van uw verzoek of klacht. Meer informatie over de persoonsgegevens die wij van sociale-netwerkproviders ontvangen en over het wijzigen van uw instellingen, vindt u op de website en in het privacybeleid van deze providers.</p><br>
                    <span>(I) Informatie die u met ons wilt delen</span>
                    <p>Wij verwerken de informatie die u op eigen initiatief met ons deelt, bijvoorbeeld als u uw interesses en voorkeuren kenbaar maakt op onze website, een reactie plaatst op onze Facebook-pagina, meedoet aan een klantenonderzoek of zich inschrijft voor een prijsvraag.</p><br>
                    <span>(J) Passagiers die overlast veroorzaken</span>
                    <p>CRUDAirlines houdt een lijst bij van passagiers die niet welkom zijn aan boord omdat zij ooit overlast hebben veroorzaakt op de grond of aan boord. Onder overlast wordt verstaan handelen in strijd met de veiligheid, verstoring van de openbare orde, toebrengen van letsel aan grondpersoneel, crew of passagiers en toebrengen van schade aan onze eigendommen. Hetzelfde geldt voor passagiers die misbruik maken van onze diensten (met inbegrip van de loyaliteitsprogramma's Flying CRUD en CRUDbiz). Op deze lijst staan de namen van de passagiers, hun geboortedatum en ticketnummer en een korte beschrijving van de incidenten en de ernst van de overlast of het misbruik. Zie voor meer informatie paragraaf 4.1 (G) hieronder.</p><br>
                    <h2>2.2 Speciale categorieën persoonsgegevens</h2><br>
                    <p>Voor bepaalde categorieën persoonsgegevens, zoals gegevens waaruit ras, etnische afkomst, geloof of levensovertuiging blijken, gegevens over uw gezondheid of strafrechtelijke gegevens, gelden op grond van de toepasselijke privacywetgeving strengere regels. Wij verwerken deze categorieën persoonsgegevens bijvoorbeeld om u tijdens de reis de door u benodigde hulp of medische faciliteiten te bieden, om te voldoen aan uw verzoeken, ten behoeve van de veiligheid aan boord of om aan wettelijke voorschriften te voldoen. Ook voor biometrische gegevens gelden strengere regels. Zoals toegelicht onder 2.1 (D) verwerken wij normaliter echter geen biometrische gegevens.</p><br>
                    <p>Dit privacybeleid is niet van toepassing op de diensten van CRUDAirlines Health Services. Deze diensten staan los van onze dienstverlening.</p><br>
                    <h2>2.3 Kinderen onder de 16 jaar</h2><br>
                    <p>Wij verzamelen gegevens over kinderen als u in verband met het boeken van een vlucht of de aankoop van een dienst of product gegevens aan ons verstrekt over uw kind. Als een kind alleen reist, registreren wij niet alleen de contactgegevens van de ouder(s) of wettelijk vertegenwoordiger(s), maar ook de contactgegevens van degene die het kind naar het de luchthaven brengt of daar ophaalt.</p><br>
                    <h2>2.4 Specifieke diensten, mobiele apps, evenementen, prijsvragen of acties</h2><br>
                    <p>Voor specifieke diensten, mobiele apps, evenementen, prijsvragen of acties kunnen wij andere soorten gegevens verzamelen dan beschreven in dit privacybeleid. Wij informeren u hierover op het moment dat u zich voor de dienst, het evenement, de prijsvraag of de actie aanmeldt of als u de app downloadt.</p><br>
                </div>
            </div>
            <div class="privacybeleid_hoe_wij_gegevens_verzamelen">
                <button class="accordion">3. Hoe wij uw gegevens verzamelen</button>
                <div class="panel"><br>
                    <p>Wij verzamelen de hiervoor genoemde categorieën van persoonsgegevens als volgt:</p><br>
                    <span>(A) Door u verstrekte persoonsgegevens</span>
                    <p>Wanneer u een vlucht bij ons boekt, een online account aanmaakt, zich aanmeldt voor ons zakelijke loyaliteitsprogramma CRUDbiz, via sociale media contact met ons opneemt, deelneemt aan een klantenonderzoek, contact opneemt met onze klantenservice, zich inschrijft voor onze e-mails of mobiele pushberichten of zich aanmeldt voor een van onze evenementen of acties.</p><br>
                    <span>(B) Persoonsgegevens die wij ontvangen van uw reisagent, onze airline partners en overige bedrijven die betrokken zijn bij uw reis</span>
                    <p>Wij ontvangen uw gegevens van deze partijen om uw reserveringen en boekingen af te handelen en uw reizen en aankopen mogelijk te maken. Als u bijvoorbeeld een vlucht boekt via een reisagent of online platform, ontvangen wij uw identiteits-, contact- en boekingsgegevens van deze derden.</p><br>
                    <span>(C) Persoonsgegevens die wij ontvangen van partners die deelnemen aan ons zakelijke loyaliteitsprogramma</span>
                    <p>Het zakelijke loyaliteitsprogramma CRUDbiz wordt aangeboden door CRUDAirlines en Air CRUD (zie ook hierboven onder ‘Wie wij zijn’). Met dit loyaliteitsprogramma kunt u CRUDcoins sparen en besteden bij CRUDAirlines en Air CRUD en bij onze loyaliteitspartners. Met het oog daarop worden de boekingsgegevens in het kader van onze boekingsprocedures (zie 2.1 (C) hierboven) onderling door Air CRUD en CRUDcoins uitgewisseld. Wij verstrekken uw persoonsgegevens ook aan onze loyaliteitspartners. Als u bijvoorbeeld een dienst afneemt bij één van onze loyaliteitspartners, delen zij de CRUDcoins die u heeft gespaard met ons zodat wij uw saldo kunnen aanpassen.</p><br>
                    <span>(D) Als u onze website of mobiele apps gebruikt, verzamelen wij informatie via cookies en vergelijkbare technologieën</span>
                    <p>CRUDAirlines maakt gebruik van eigen cookies en van cookies van derden. Meer informatie hierover vindt u in ons cookiebeleid. </p><br>
                    <span>(E) Als u gebruikmaakt van een sociaal netwerk, kunnen wij ook gegevens ontvangen van uw sociale-netwerkprovider</span>
                    <p>Zie voor meer informatie paragraaf 2.1 (H) hierboven.</p><br>
                    <span>(F) Wij ontvangen bepaalde informatie van de overheid of van overheidsinstanties ten behoeve van de veiligheid aan boord</span>
                    <p>CRUDAirlines ontvangt de namen van personen die door de Staat der Nederlanden of een overheidsinstantie op een zwarte lijst zijn geplaatst. Dit gebeurt bijvoorbeeld bij passagiers die uitstappen op Schiphol en bij wie door de Koninklijke Marechaussee drugs zijn aangetroffen. Zie voor meer informatie paragraaf 4.1 (G) hierna.</p><br>
                </div>
            </div>
            <div class="privacybeleid_doeleinden">
                <button class="accordion">4. De doeleinden waarvoor wij u gegevens gebruiken</button>
                <div class="panel"><br>
                    <h2>4.1. De belangrijkste doeleinden waarvoor wij uw gegevens gebruiken</h2><br>
                    <span>(A) Om onze diensten aan u te leveren</span>
                    <p>Wij gebruiken de onder 2.1 (A) tot en met (G) beschreven informatie om uw reserveringen en boekingen af te handelen en uw reizen en aankopen mogelijk te maken. We maken bijvoorbeeld gebruik van uw naam, paspoortnummer en andere identiteitsgegevens om uw ticket te kunnen verstrekken. Wij gebruiken uw contactgegevens om wijzigingen in de vluchtstatus aan u door te geven.Als de personen in uw boeking deelnemen aan ons loyaliteitsprogramma Flying CRUD, gebruiken wij de door hen verstrekte contactgegevens om hen te informeren over hun vlucht en over eventuele wijzigingen in de vluchtstatus.</p><br>
                    <p>Informatie over uw specifieke medische behoeften hebben wij nodig om ervoor te kunnen zorgen dat u de juiste zorg ontvangt. Deze gegevens gebruiken wij alleen om te zorgen dat u de juiste zorg ontvangt.</p><br>
                    <span>(B) Om ons zakelijke loyaliteitsprogramma CRUDbiz uit te voeren</span><br>
                    <span>(C) Om onze online diensten en mobiele apps aan u te leveren en te zorgen voor een geruisloze digitale ervaring</span>
                    <p>i. Wij gebruiken uw naam en vluchtgegevens bijvoorbeeld als u met onze app incheckt voor uw vlucht.</p><br>
                    <p>ii. Bij onze online diensten en apps wordt soms gebruikgemaakt van uw locatie, bijvoorbeeld om u de dichtstbijzijnde bezienswaardigheid te laten zien.</p><br>
                    <p>iii. Om u een optimale digitale ervaring te bieden, analyseren wij uw digitale-mediagebruik. Zo stemmen we bijvoorbeeld onze communicatie af op het digitale kanaal of apparaat dat u het meest gebruikt (zie 2.1 (G)).</p><br>
                    <p>iv. Als u uw boekingsprocedure afbreekt op onze website, sturen wij u een e-mail met een link naar uw boekingsprocedure, zodat u kunt doorgaan waar u was gebleven. U ontvangt een vergelijkbare mail als u de boekingsprocedure afbreekt op de website van onze partners Airtrade of OptionTown, die package deals en flight bundels aanbieden. We sturen deze e-mails alleen op uw verzoek of als u akkoord bent gegaan met het per e-mail ontvangen van updates en speciale aanbiedingen (zie 4.1 (E)). U kunt uw toestemming voor deze e-mails op elk moment intrekken door op de afmeldlink in de e-mail te klikken, door uw communicatievoorkeuren in uw account aan te passen (indien beschikbaar) of door contact met ons op te nemen (zie paragraaf 8 ‘Uw rechten’ hieronder).</p><br>
                    <span>(D) Voor statisch onderzoek</span>
                    <p>i. Algemeen: we doen onderzoek naar algemene trends in het gebruik van onze diensten, loyaliteitsprogramma’s, websites, mobiele apps en sociale media en in het gedrag en de voorkeuren van onze klanten, deelnemers aan onze loyaliteitsprogramma's en gebruikers. We gebruiken de onderzoeksresultaten om betere diensten en aanbiedingen voor onze klanten te ontwikkelen, de loyaliteitsprogramma’s te verbeteren, onze klantenservice aan te scherpen en het ontwerp en de inhoud van onze websites en mobiele apps te verbeteren.
                        ii. Gegevenscategorieën: voor ons onderzoek kunnen we gebruikmaken van de in paragraaf 2.1 (A) tot en met (I) beschreven categorieën persoonsgegevens en van de persoonsgegevens die wij registreren als u deelneemt aan Flying CRUD (zie voor meer informatie het Flying CRUD-privacybeleid). Voor het onderzoek gebruiken we alleen ‘geaggregeerde’ en ‘gepseudonimiseerde’ gegevens. Dit zijn gegevens die niet direct tot u herleidbaar zijn en waaruit alle direct identificeerbare elementen (zoals naam en e-mailadres) zijn verwijderd of omgecodeerd zijn tot een nummer. We treffen passende maatregelen om ervoor te zorgen dat slechts een beperkte groep werknemers toegang heeft tot de dataset.
                        iii. Voorbeeld: uit ons onderzoek naar boekingsgegevens en gegevens over de aankoop van aanvullende diensten (extra bagage, upgrades) kan bijvoorbeeld blijken dat langeafstandsreizigers vaker extra beenruimte kopen. Met deze informatie kunnen we onze diensten verbeteren, bijvoorbeeld door de mogelijkheid van extra beenruimte bij langeafstandsvluchten extra onder de aandacht te brengen.
                        iv. Wettelijke grondslag en recht van bezwaar: wij verwerken uw persoonsgegevens in het kader van de hierboven beschreven gerechtvaardigde belangen (zie paragraaf (i) ‘Algemeen’). U heeft op grond van met uw specifieke situatie verband houdende redenen te allen tijde het recht om bezwaar te maken tegen de verwerking van uw persoonsgegevens voor statistisch onderzoek (zie paragraaf 8 ‘Uw rechten’ hieronder).
                    </p><br>
                    <span>(E) Marketingdoeleinden</span>
                    <p>i. Algemeen: wij kunnen uw persoonsgegevens gebruiken voor direct marketing-doeleinden. In deze paragraaf leggen wij uit hoe we dat doen.</p><br>
                    <p>ii. Kanalen: wij maken gebruik van diverse kanalen zoals e-mail, mobiele pushberichten, gewone post en advertentieruimte op websites en sociale media. Bijvoorbeeld:</p><br>
                    <p>– Boekingsgerelateerde e-mails: als u een vlucht bij ons boekt, ontvangt u verschillende e-mails in verband met uw boeking (zoals een boekingsbevestiging, informatie over inchecken en boarden). Deze mails bevatten ook advertenties en aanbiedingen die op u en uw vlucht zijn afgestemd.</p><br>
                    <p>– E-mails van CRUDAirlines met updates en aanbiedingen: u kunt zich aanmelden voor e-mails met updates en aanbiedingen die op uw interesses zijn afgestemd, zoals onze nieuwsbrief. Deze e-mails bevatten aanbiedingen voor onze eigen diensten en die van onze partners, zoals de package deals en flight bundels van onze partners Airtrade en OptionTown. Met uw toestemming sturen wij u ook e-mails bij specifieke gelegenheden, zoals een speciale aanbieding op uw verjaardag of gepersonaliseerde aanbiedingen voor uw volgende reis binnen enkele maanden na uw terugkeer.</p><br>
                    <p>– Rechtstreekse berichten via andere communicatiekanalen: met uw toestemming maken wij gebruik van andere communicatiekanalen om u rechtstreeks berichten te sturen met gepersonaliseerde advertenties en speciale aanbiedingen, zoals per post, mobiele pushberichten of via sociale media (zoals Messenger, WhatsApp of WeChat).</p><br>
                    <p>– Tonen van relevante informatie en gepersonaliseerde advertenties op websites en apps: zie ons cookiebeleid. Wij kunnen uw persoonsgegevens ook gebruiken om u uit te sluiten van advertenties die voor u niet langer relevant zijn.</p><br>
                    <p>– Gerichte marketing via sociale-mediaplatformen ('custom audience targeting’): u kunt zich aanmelden om gepersonaliseerde advertenties en aanbiedingen te ontvangen via de sociale-mediaplatformen die u gebruikt. </p><br>
                    <p>Wij maken bijvoorbeeld gebruik van het Facebook Custom Audience-programma. Met dit programma kunnen we onder meer gepersonaliseerde advertenties en aanbiedingen tonen in uw nieuwsoverzicht op platformen van Facebook, zoals Facebook Messenger en Instagram. Ook kunnen we u met dit programma uitsluiten van advertentiecampagnes op de platformen van Facebook, bijvoorbeeld wanneer u al via e-mail vergelijkbare advertenties of aanbiedingen heeft ontvangen.</p><br>
                    <p>We verstrekken uw gepseudonimiseerde (‘gehashte’) e-mailadres aan Facebook zodat Facebook kan controleren of u een Facebook-account heeft. Verder verstrekken wij geen andere gegevens aan Facebook. Omgekeerd verstrekt Facebook uitsluitend geaggregeerde gegevens aan ons over de effectiviteit van een advertentiecampagne. Deze gegevens zijn niet direct tot u herleidbaar. Op deze manier zetten we ons naar beste vermogen in om uw persoonsgegevens vertrouwelijk en veilig te houden.</p><br>
                    <p>Om ons publiek (‘audience’) voor een specifieke Facebook-campagne te bepalen, kunnen we gebruikmaken van uw boekingsgegevens of van de gegevens die we registreren als u onze websites, mobiele apps of andere digitale media gebruikt. Daarnaast kan Facebook de persoonsgegevens die Facebook van u heeft vastgelegd, gebruiken om een vergelijkbaar publiek te selecteren. Daarmee kunnen we via Facebook een nieuw publiek bereiken.</p><br>
                    <p>Wij kunnen deelnemen aan vergelijkbare programma's van andere sociale-medianetwerken, zoals Google, Twitter, LinkedIn, Pinterest, Snapchat, WeChat, Kakaotalk en LINE. Voor meer informatie verwijzen wij u naar het privacybeleid van het desbetreffende sociale-medianetwerk.</p><br>
                    <p>iii. Gepersonaliseerde aanbiedingen: we proberen advertenties en aanbiedingen zo relevant mogelijk voor u te maken. Met het oog daarop kunnen we analyses uitvoeren op de in paragraaf 2.1 (A) tot en met (I) en 4.1 (C) (statistisch onderzoek) beschreven categorieën persoonsgegevens en de persoonsgegevens die wij registreren als u deelneemt aan Flying CRUD (zie voor meer informatie het Flying CRUD-privacybeleid). De analyseresultaten gebruiken wij om advertenties en aanbiedingen te personaliseren. Als u weer thuis bent na een reis, kunnen wij u met uw toestemming bijvoorbeeld een e-mail sturen met aanbiedingen op basis van uw boekingsgeschiedenis, waarmee u inspiratie kunt opdoen voor een volgende reis. Wij kunnen uw boekingsgeschiedenis (zakelijk of particulier reizen, reisklasse, bestemming, deelnemer Flying CRUD) ook gebruiken om u korting te geven op een upgrade of extra bagage.</p><br>
                    <p>iv. Wettelijke grondslag en recht van bezwaar: tenzij anders aangegeven, verwerken wij uw persoonsgegevens als beschreven in deze paragraaf 4.1 (E) voor onze gerechtvaardigde belangen en voor de belangen van derden. U heeft te allen tijde het recht om bezwaar te maken tegen het gebruik van uw persoonsgegevens voor direct marketing en gerelateerde profileringsactiviteiten (zie paragraaf 8 ‘Uw rechten’ hieronder).</p><br>
                    <p>v. Afmelden: u kunt zich altijd afmelden voor gepersonaliseerde advertenties en aanbiedingen. Hieronder wordt uitgelegd hoe u zich kunt afmelden.</p><br>
                    <p>– Per e-mail: u kunt zich op elk moment afmelden voor advertenties en aanbiedingen in onze e-mails betreffende uw boeking en onze loyaliteitsprogramma's en voor e-mails waarvoor u zich heeft aangemeld, door op de afmeldlink in de e-mail te klikken. In veel gevallen kunt u zich ook afmelden door uw communicatievoorkeuren in uw account aan te passen. Als u zich afmeldt, ontvangt u alleen nog e-mails die noodzakelijk zijn om van onze diensten gebruik te kunnen maken (zoals uw boekingsbevestiging en e-ticket) en om aan ons loyaliteitsprogramma te kunnen deelnemen (zoals een welkomstbericht aan deelnemers).</p><br>
                    <p>– Per post: u kunt zich afmelden voor gepersonaliseerde advertenties en speciale aanbiedingen door via de post contact met ons op te nemen (zie paragraaf 8 ‘Uw rechten’ hieronder).</p><br>
                    <p>– Via andere communicatiekanalen: als u zich heeft aangemeld voor gepersonaliseerde advertenties en aanbiedingen via mobiele pushberichten, kunt u zich afmelden door de instellingen op uw smartphone (voor mobiele pushberichten) aan te passen. Meer informatie over het afmelden voor gepersonaliseerde advertenties en aanbiedingen via sociale media (zoals Messenger, WhatsApp en WeChat) vindt u op de website van uw sociale-netwerkprovider.</p><br>
                    <p>– Door contact op te nemen met onze Privacy Offices: u kunt zich altijd afmelden voor berichten met advertenties en aanbiedingen door contact met ons op te nemen (zie paragraaf 8 ‘Uw rechten’ hieronder).</p><br>
                    <span>(F) Om met u te communiceren</span><br>
                    <p>Wij gebruiken uw contactgegevens om met u te communiceren over onze diensten of het loyaliteitsprogramma, om uw vragen te beantwoorden of om uw klachten te behandelen.</p><br>
                    <span>(G) Passagiers die overlast veroorzaken</span>
                    <p>i. Passagiers die op de grond of aan boord overlast veroorzaken of misbruik maken van onze diensten, kunnen voor maximaal vijf jaar worden uitgesloten op onze vluchten, of zijn uitsluitend onder bepaalde voorwaarden welkom aan boord. CRUDAirlines houdt een lijst bij van passagiers die overlast hebben veroorzaakt (zie 2.1 (J) hierboven). De passagiers op deze lijst worden persoonlijk (zo mogelijk schriftelijk) geïnformeerd over het feit dat zij op deze lijst zijn geplaatst, waarom dat het geval is, welke maatregelen CRUDAirlines jegens hen heeft genomen en hoe lang deze bijzondere veiligheidsmaatregelen op hen van toepassing zijn. Meer informatie over inzage in of correctie van deze gegevens vindt u hieronder in paragraaf 8 ‘Uw rechten’.</p><br>
                    <p>ii. Illegale drugs: CRUDAirlines ontvangt van de Staat der Nederlanden de namen van passagiers die op Schiphol zijn uitgestapt en bij wie door de Koninklijke Marechaussee illegale drugs zijn aangetroffen. CRUDAirlines kan gedurende een periode van 3 jaar weigeren om deze personen te vervoeren op rechtstreekse vluchten vanaf Schiphol naar Suriname, Aruba, Bonaire, St. Maarten of Curaçao en op rechtstreekse vluchten vanuit deze landen naar Schiphol. U kunt inzage in of correctie van deze gegevens aanvragen door een schriftelijk verzoek daartoe in te dienen bij de Koninklijke Marechaussee, Postbus 90615, 2509 LP Den Haag. Indien u woonachtig bent op Aruba, de Nederlandse Antillen, in Suriname of in Venezuela dient u bij dit schriftelijke verzoek een kopie van uw paspoort mee te sturen. </p><br>
                    <span>(H) Voor onze bedrijfsvoering of om aan wettelijke verplichtingen te voldoen</span>
                    <p>We verzamelen, gebruiken en bewaren uw persoonsgegevens voor onze bedrijfsvoering, zoals onze administratie, voor fraudepreventie en -bestrijding of voor geschillenbeslechting. Bij fraude of misbruik van onze diensten kunnen wij uw persoonsgegevens opnemen in onze interne fraudebeheersings- en waarschuwingssystemen. Als gevolg daarvan kunnen we uw boekingen aan een nader onderzoek onderwerpen en deze in sommige gevallen weigeren of annuleren. Of we kunnen besluiten dat u niet langer welkom bent aan boord of uitsluitend onder bepaalde voorwaarden (zie 4.1 (G) hierboven). We verwerken uw persoonsgegevens ook ten behoeve van de naleving van onze wettelijke en fiscale verplichtingen.</p><br>
                    <h2>4.2 Specifieke diensten, apps, evenementen, prijsvragen of acties</h2><br>
                    <p>Voor specifieke diensten, apps, evenementen, prijsvragen of acties kunnen wij gebruikmaken van andere soorten gegevens dan beschreven in dit privacybeleid. Wij informeren u hierover op het moment dat u zich voor de dienst, het evenement, de prijsvraag of de actie registreert of als u de app downloadt.</p><br>
                    <h2>4.3 Wettelijke grondslag</h2><br>
                    <p>We kunnen uw persoonsgegevens uitsluitend verwerken als wij daarvoor een wettelijke grondslag hebben. In veel gevallen hebben wij uw persoonsgegevens nodig om uw boeking in ontvangst te nemen en te verwerken, uw vlucht of aankopen te verzorgen, uw deelname aan onze loyaliteitsprogramma's mogelijk te maken of om uw vragen te beantwoorden (zie 4.1 (A) tot en met (B) en (F) hierboven). Wij verwerken uw gegevens dan op de rechtsgrond ‘noodzakelijk voor de uitvoering van een overeenkomst’.</p><br>
                    <p>Als u toestemming heeft gegeven voor de verwerking van uw persoonsgegevens (welke toestemming u te allen tijde weer kunt intrekken, zie paragraaf 8 ‘Uw rechten’ hieronder), verwerken wij uw gegevens op basis van die toestemming.</p><br>
                    <p>In bepaalde gevallen kunnen wij uw persoonsgegevens gebruiken als wij of derden daarbij een gerechtvaardigd belang hebben. Wij maken altijd een zorgvuldige afweging van alle belangen: uw belangen, die van anderen en die van CRUDAirlines. Op deze laatste grondslag verwerken wij uw gegevens bijvoorbeeld voor beveiligingsdoeleinden, statistisch onderzoek, direct marketing of gepersonaliseerde kortingen en aanbiedingen (zie 4.1 (C), (D) en (G) hierboven voor meer informatie).</p><br>
                    <p>Wij kunnen een wettelijke plicht hebben om uw gegevens te verwerken, bijvoorbeeld om te voldoen aan immigratieformaliteiten (zie 4.1 (H)).</p><br>
                    <p>Indien u weigert om de persoonsgegevens te verstrekken die we nodig hebben voor de uitvoering van de overeenkomst die we met u hebben gesloten of voor de naleving van een wettelijke verplichting, kunnen we mogelijk niet alle diensten leveren waarom u heeft verzocht. Dan moeten we bijvoorbeeld uw boeking annuleren of kunnen we de door u gewenste aanvullende diensten niet leveren. Als u onvolledige of onjuiste gegevens heeft verstrekt, kunnen wij ons genoodzaakt zien om u de toegang tot uw vlucht te ontzeggen of het betreden van buitenlands grondgebied te weigeren.</p><br>
                </div>
            </div>
            <div class="privacybeleid_verlenen_inzage_en_uitwisseling">
                <button class="accordion">5. Verlenen van inzage aan of uitwisseling van gegevens met derden</button>
                <div class="panel"><br>
                    <h2>5.1. Algemeen</h2>
                    <p>Wij kunnen uw persoonsgegevens in de volgende gevallen aan derden verstrekken:</p><br>
                    <span>(A) Voor het faciliteren van uw boekingen en reizen</span>
                    <p>Om uw reserveringen en boekingen af te handelen en uw reizen en aankopen mogelijk te maken, moeten wij uw persoonsgegevens in veel gevallen uitwisselen met onze partnerairlines, luchthavenexploitanten en andere bedrijven die bij uw reis betrokken zijn (zie 3.1 (B) hierboven, ‘Hoe wij uw gegevens verzamelen’).</p><br>
                    <span>(B) Ten behoeve van ons zakelijke loyaliteitsprogramma CRUDbiz</span>
                    <p>Zie voor meer informatie de paragraaf ‘Wie wij zijn’ en 3.1 (C) onder ‘Hoe wij uw gegevens verzamelen’.</p><br>
                    <span>(C) Zakelijke accounts</span>
                    <p>Als u een vlucht boekt via de zakelijke account van uw werkgever, heeft uw werkgever toegang tot bepaalde boekingsgegevens, zoals de prijs van het ticket, de reisdata en uw bestemming. Uw werkgever is zelfstandig verantwoordelijk voor de wijze waarop hij uw persoonsgegevens verwerkt en u daarover informeert.</p><br>
                    <span>(D) Voor ondersteunende of aanvullende diensten</span>
                    <p>Om onze diensten te leveren, maken wij gebruik van ondersteunende of aanvullende diensten van derden, zoals IT-leveranciers, sociale-media-providers en marketing- en screeningbureaus. Al deze derden zijn verplicht uw persoonsgegevens afdoende te beschermen en deze alleen te verwerken overeenkomstig onze instructies.</p><br>
                    <p>Binnen de Air CRUD-CRUDAirlines Groep wordt voor de bedrijfsvoering gebruikgemaakt van gecentraliseerde databases en systemen. Deze centrale databases en systemen kunnen door een van de groepsmaatschappijen worden gehost of beheerd voor de andere groepsmaatschappijen. Daarnaast kunnen bepaalde operationele functies ten behoeve van de efficiency door een van de groepsmaatschappijen worden uitgevoerd voor de andere groepsmaatschappijen. Dit betekent dat onze groepsmaatschappijen in dat kader toegang kunnen hebben tot uw persoonsgegevens. Onze groepsmaatschappijen mogen uw persoonsgegevens alleen verwerken wanneer dat nodig is voor de betreffende bedrijfsfunctie en overeenkomstig dit privacybeleid.</p><br>
                    <span>(E) Betaaldiensten</span>
                    <p>Om de betaling van uw reizen en aankopen te verwerken, kunnen wij samenwerken met derden die betaaldiensten aanbieden. Deze aanbieders controleren in veel gevallen ook op fraude. Zij hanteren een eigen privacybeleid wat betreft de wijze waarop zij van uw persoonsgegevens gebruikmaken.</p><br>
                    <span>(F) Gepersonaliseerde marketing via sociale-mediaplatformen</span>
                    <p>Zie voor meer informatie paragraaf 4.1 (E) onder ‘De doeleinden waarvoor wij uw gegevens gebruiken’.</p><br>
                    <span>(G) Zodat onze partners hun aanbod kunnen afstemmen op uw reis</span><br>
                    <p>Wij kunnen uw niet-persoonlijke gegevens (bestemming, reisdatum en reisduur) uitwisselen met partners die aanvullende diensten aanbieden (zoals hotelovernachtingen, autoverhuur) zodat zij hun aanbod kunnen afstemmen op uw reis. Zij hanteren een eigen privacybeleid wat betreft de wijze waarop zij van uw persoonsgegevens gebruikmaken.</p><br>
                    <h2>5.2. Specifieke diensten, apps, evenementen, prijsvragen of acties</h2><br>
                    <p>Voor specifieke diensten, apps, evenementen, prijsvragen of acties kunnen wij uw gegevens uitwisselen met andere derden dan beschreven in dit privacybeleid. Bijvoorbeeld als we een actie of evenement samen met een partner organiseren of wij hun diensten integreren in onze apps. Wij informeren u hierover op het moment dat u zich voor de dienst, het evenement, de prijsvraag of de actie aanmeldt of als u de app downloadt.</p><br>
                    <h2>5.3. Overheidsinstanties</h2><br>
                    <span>(A) Algemeen</span>
                    <p>We kunnen wettelijk verplicht zijn om uw persoonsgegevens te verzamelen voordat u naar een ander land reist en deze gegevens te verstrekken aan de overheidsinstanties in de landen van uw reisschema. Zo kunnen we wettelijk verplicht zijn om uw identiteitsgegevens en uw boekings- en reisgegevens aan deze overheidsinstanties door te geven ten behoeve van grenscontroles, immigratieformaliteiten, het betreden van het grondgebied van het betreffende land of de bestrijding van terrorisme en andere zware misdrijven (zie 5.3 (B) hierna). Ook kunnen wij wettelijk verplicht zijn om uw gezondheidsgegevens door te geven aan de overheidsinstanties in de landen van uw reisschema om redenen van volksgezondheid (zie 2.1 (D) hierboven). </p><br>
                    <span>(B) PNR- en API-gegevens</span>
                    <p>i. Algemeen: ingevolge de Europese verordeningen 2016/679 en 2004/82 en de toepasselijke lokale wet- en regelgeving zijn wij verplicht om PNR- en API-gegevens door te geven aan overheidsorganen, zoals de Passenger Information Units (PIU’s) in diverse landen. API (Advance Passenger Information) betreft informatie over uw vlucht en uw paspoortgegevens. PNR (Passenger Name Record) betreft alle informatie over uw boekingen, zoals vluchtgegevens, passagiers in de boeking en betaalgegevens. Wij geven deze PNR-gegevens voor alle vluchten door aan de Nederlandse PIU (Pi-NL). Als dit vereist is, geven we de API- en PNR-gegevens ook door aan de instanties in landen buiten Nederland.</p><br>
                    <p>ii. Landenspecifiek:</p><br>
                    <p>- Frankrijk: ingevolge artikel L 237 -7 van de Franse binnenlandse veiligheidswet kan CRUDAirlines verplicht zijn om uw reserverings-, incheck- en boardinggegevens (API/PNR) door te geven aan de bevoegde nationale instanties in Frankrijk voor de doeleinden en onder de voorwaarden als beschreven in Besluit nr. 2014-1095 van 26 september 2014, zoals nadien gewijzigd bij Besluit nr. 2018/714 van 3 augustus 2018. </p><br>
                    <h2>5.4. Websites van derden</h2>
                    <p>Onze websites en mobiele apps bevatten links naar websites van derden. Als u deze links volgt, verlaat u onze websites of mobiele apps. Dit privacybeleid is niet van toepassing op de websites van derden. Meer informatie over hoe derden met uw persoonsgegevens omgaan, vindt u in hun privacy- en/of cookiebeleid (indien beschikbaar).</p><br>
                </div>
            </div>
            <div class="privacybeleid_veiligheid">
                <button class="accordion">6. Veiligheid</button>
                <div class="panel"><br>
                    <h2>6.1. Veiligheid</h2>
                    <span>(A) Onze inzet</span>
                    <p>Borging van de veiligheid en vertrouwelijkheid van uw persoonsgegevens heeft bij ons prioriteit. Rekening houdend met de aard van uw persoonsgegevens en de risico's van verwerking, hebben wij alle passende technische en organisatorische maatregelen getroffen die vereist zijn op grond van de geldende wettelijke voorschriften (met name artikel 32 van de Algemene Verordening Gegevensbescherming (AVG)), zodat een passend veiligheidsniveau is geborgd en met name ter voorkoming van onbedoelde of onrechtmatige vernietiging, verlies, wijziging of verstrekking van, inbreuk op of onbevoegde toegang tot deze gegevens.</p><br>
                    <span>(B) De veiligheidsmaatregelen die wij hebben getroffen</span>
                    <p>i. Banktransacties: wij zijn verplicht om te voldoen aan het bepaalde in de Data Security Standard for the Payment Card Industry (de PCI DSS-standaard) van de PCI Security Standards Council (PCI SSC). Deze standaard is ontwikkeld om meer controle te krijgen over de gegevens van pashouders en om fraude met betaalinstrumenten aan te pakken. Alle dienstverleners van CRUDAirlines die bankpasgegevens verwerken, dienen aan deze PCI DSS-standaard te voldoen. We willen identiteitsdiefstal op internet zo veel mogelijk tegengaan. Om die reden maken we bijvoorbeeld gebruik van apparatuur om frauduleuze betalingen te signaleren, zodat u in geval van verlies of diefstal van uw bankpas bent beschermd.</p><br>
                    <p>ii. Organisatorische maatregelen: wij hebben diverse organisatorische maatregelen getroffen ter vergroting van de alertheid bij onze medewerkers en ten behoeve van de verantwoording. Er zijn programma's geïntroduceerd die zorgen voor een groter bewustzijn en tegelijk de uitwisseling van ‘good practices’ en veiligheidsstandaarden bevorderen. In dat kader hebben onze medewerkers toegang tot een breed scala aan documenten over informatiebeveiliging en privacybescherming en alles wat daarbij komt kijken.</p><br>
                    <p>iii. Technische maatregelen: we houden streng toezicht op de fysieke en logische toegang tot de interne servers waarop uw persoonsgegevens gehost of verwerkt worden. We beveiligen ons netwerk met de nieuwste hardware (Firewall, IDS, DLP etc.) en architectuur (met inbegrip van veiligheidsprotocollen zoals TLS 1.2) om de risico's van cybercriminaliteit te voorkomen en te beperken.</p><br>
                    <span>(C) De ontwikkeling van onze beveiligingssystemen</span>
                    <p>Om een passend veiligheidsniveau te handhaven, beschikken wij over interne processen volgens de beste standaarden (met name de ISO 27000-standaarden). We maken gebruik van ter zake kundige professionals om een zo hoog mogelijk beschermingsniveau te borgen. In dat kader onderhouden wij een speciale relatie met het NCSC (National Cyber Security Centre).</p><br>
                    <span>(D) Wat u zelf kunt doen</span>
                    <p>Bij de beveiliging en geheimhouding van persoonsgegevens draait het om een optimale inzet van alle betrokkenen. Wanneer u een reservering maakt, ontvangt u bestandsreferenties. Deze boekingsreferenties dienen te allen tijde geheim te blijven. Als deze referenties bij andere passagiers terechtkomen, kunnen zij uw boekingsgegevens inzien via onze systemen of die van derden die bij de uitvoering van uw reis zijn betrokken (zoals reisbureaus en online zoek- en boekingssites). Als u samen reist en niet wilt dat uw reisgenoten inzage hebben in uw persoonsgegevens, raden wij u aan om apart te boeken.</p><br>
                    <p>Ook adviseren wij u om de wachtwoorden die u voor onze diensten gebruikt, niet aan derden te verstrekken, om systematisch uit uw profiel en sociale account uit te loggen (zeker bij gekoppelde accounts) en om het browserscherm na afloop van uw sessie te sluiten, met name als u vanaf een openbare computer van internet gebruikmaakt. Zo voorkomt u dat andere gebruikers uw persoonsgegevens kunnen inzien. Om het risico van hacking te voorkomen, raden wij aan om voor elke online dienst waarvan u gebruikmaakt, een ander wachtwoord te gebruiken. Wij zijn niet verantwoordelijk voor diefstal van uw gegevens op een platform dat niet door ons wordt beheerd.</p><br>
                    <p>Daarnaast adviseren wij u met klem om door CRUDAirlines verstrekte bescheiden waarin uw persoonsgegevens (uw boarding pass, ticketnummer etc.) of andere gegevens over uw reis zijn opgenomen, niet aan derden te verstrekken en ook niet op een sociaal netwerk te publiceren. Als u deze bescheiden toch op sociale media plaatst, dient u bekend te zijn met de algemene gebruiksvoorwaarden, de informatiebeveiliging en het privacybeleid van de betreffende netwerkaanbieders. Wij zijn niet verantwoordelijk voor de wijze waarop uw gegevens op een dergelijk platform worden verwerkt, opgeslagen of doorgegeven.</p><br>
                    <span>(E) Beheersing van veiligheidsincidenten</span>
                    <p>'Nul risico' bestaat niet en zelfs als we alle passende veiligheidsmaatregelen treffen, kunnen er nog onvoorziene dingen gebeuren. Wij beschikken over specifieke procedures en middelen om veiligheidsincidenten zo goed mogelijk te beheersen.Daarnaast hanteren we een specifieke procedure voor het beoordelen van potentiële datalekken die kunnen resulteren in onbedoelde of onrechtmatige vernietiging, verlies, wijziging of onbevoegde verstrekking van of toegang tot uw persoonsgegevens, voor het tijdig melden van datalekken bij de bevoegde toezichthouder en aan u als we denken dat het datalek een hoog risico inhoudt voor uw rechten en vrijheden. We testen periodiek of de veiligheidsinstallaties functioneren en of de gehanteerde procedures en apparatuur afdoende zijn.</p><br>
                    <h2>6.2. Bewaring</h2>
                    <p>Wij bewaren uw persoonsgegevens niet langer dan noodzakelijk is. Hoe lang uw persoonsgegevens worden bewaard, hangt af van de doeleinden waarvoor deze gegevens worden verwerkt en van de geldende wettelijke bewaartermijn.</p><br>
                </div>
            </div>
            <div class="privacybeleid_internationale_doorgifte">
                <button class="accordion">7. Internatiole doorgifte van gegevens</button>
                <div class="panel"><br>
                    <p>7.1. CRUDAirlines kan uw persoonsgegevens doorgeven aan andere landen dan het land waar u woont. Dat doen we om uw boeking af te handelen of uw reis te verzorgen of omdat onze groepsmaatschappijen, partners of dienstverleners hun werkzaamheden vanuit een ander land verrichten.</p><br>
                    <p>7.2. Als u vliegt naar een bestemming in een ander land dan waar u woont, is de doorgifte van uw persoonsgegevens naar dat land vaak noodzakelijk om onze diensten aan u te kunnen leveren. Zo nodig zorgt CRUDAirlines ervoor dat er sprake is van passende waarborgen, zodat voldaan wordt aan de vereisten voor de internationale doorgifte van persoonsgegevens ingevolge de geldende privacywetgeving. Voor de doorgifte van persoonsgegevens naar landen buiten de Europese Economische Ruimte kan CRUDAirlines gebruikmaken van door de Europese Commissie goedgekeurde modelcontractbepalingen als passende waarborg.</p><br>
                    <p>7.3. We kunnen wettelijk verplicht zijn om uw persoonsgegevens door te geven aan overheidsinstanties in de landen van uw reisschema (zie 5.3 hierboven).</p><br>
                </div>
            </div>
            <div class="privacybeleid_uw_rechten">
                <button class="accordion">8. Uw rechten</button>
                <div class="panel"><br>
                    <p>8.1. Door contact op te nemen met ons Privacy Office (zie 8.4 hieronder) kunt u alle rechten uitoefenen die u volgens de geldende privacywetgeving toekomen, waaronder (A) het inzien van uw gegevens, (B) het rectificeren van uw gegevens, (C) het wissen van uw gegevens, (D) het beperken van de verwerking van uw gegevens, (E) het recht op gegevensoverdraagbaarheid en (F) het recht om bezwaar te maken tegen verwerking.</p><br>
                    <span>(A) Recht van inzage</span>
                    <p>U mag ons vragen of wij uw persoonsgegevens verwerken. Is dat het geval, dan kunt u inzage in deze gegevens krijgen in de vorm van een kopie.</p><br>
                    <span>(B) Recht op rectificatie</span>
                    <p>U heeft het recht om uw gegevens te rectificeren indien deze onjuist of onvolledig zijn. Op verzoek corrigeren wij onjuiste persoonsgegevens en vullen wij onvolledige persoonsgegevens aan, rekening houdend met de verwerkingsdoeleinden; dit kan de afgifte van een aanvullende verklaring inhouden.</p><br>
                    <span>(C) Recht op gegevenswissing</span>
                    <p>U heeft het recht om uw persoonsgegevens te laten wissen. Dit betekent dat wij uw gegevens dan verwijderen. Het wissen van uw persoonsgegevens vindt alleen plaats in bepaalde gevallen, die wettelijk zijn voorgeschreven en vermeld staan in artikel 17 van de Algemene Verordening Gegevensbescherming (AVG), bijvoorbeeld wanneer uw persoonsgegevens niet langer nodig zijn voor de doeleinden waarvoor zij oorspronkelijk werden verwerkt of wanneer ze onrechtmatig zijn verwerkt. Door de wijze waarop wij bepaalde diensten hebben ingericht, kan het enige tijd duren voordat backups zijn gewist.</p><br>
                    <span>(D) Recht op beperking van verwerking</span>
                    <p>U heeft het recht om de verwerking van uw persoonsgegevens te laten beperken. Dit houdt in dat wij de verwerking van uw gegevens gedurende een bepaalde tijd opschorten. Omstandigheden die hiertoe aanleiding kunnen geven, zijn onder meer situaties waarin de juistheid van uw persoonsgegevens wordt betwist, maar wij enige tijd nodig hebben om de (on)juistheid daarvan te verifiëren. Dit recht betekent niet dat wij uw persoonsgegevens niet mogen blijven opslaan. Wij laten u weten wanneer de beperking wordt opgeheven.</p><br>
                    <span>(E) Recht op gegevensoverdraagbaarheid</span>
                    <p>Uw recht op gegevensoverdraagbaarheid houdt in dat u ons mag vragen om uw persoonsgegevens, indien dit technisch mogelijk is, in een gestructureerde, gangbare en machineleesbare vorm te verkrijgen en deze aan een andere verwerkingsverantwoordelijke over te dragen. Op verzoek en indien dit technisch mogelijk is, worden uw persoonsgegevens door ons dan rechtstreeks overgedragen aan de andere verwerkingsverantwoordelijke.</p>
                    <span>(F) Recht van bezwaar</span>
                    <p>U heeft het recht om bezwaar te maken tegen de verwerking van uw persoonsgegevens. Dit houdt in dat u ons kunt vragen om uw persoonsgegevens niet langer te verwerken. Dit geldt alleen als ‘gerechtvaardigde belangen’ (waaronder profilering) de rechtsgrond voor de verwerking vormen (zie 4.3 ‘Wettelijke grondslag’ hierboven). U kunt te allen tijde kosteloos bezwaar maken tegen direct marketing wanneer uw persoonsgegevens voor dit doel worden verwerkt. Hieronder valt ook profilering in verband met direct marketing. Als u dit recht uitoefent, verwerken wij uw persoonsgegevens niet langer voor deze doeleinden.</p><br>
                    <h2>8.2. Intrekking van uw toestemming</h2>
                    <p>U kunt uw toestemming te allen tijde intrekken door de specifieke instructies te volgen die betrekking hebben op de verwerking waarvoor u toestemming heeft gegeven. U kunt uw toestemming bijvoorbeeld intrekken door te klikken op de afmeldlink in de e-mail, door uw communicatievoorkeuren in uw account aan te passen (indien beschikbaar) of door de instellingen van uw smartphone te wijzigen (voor mobiele pushberichten en locatiegegevens)</p><br>
                    <p>U kunt ook contact opnemen met het Privacy Office van CRUDAirlines. Voor CRUDbiz e-mails kunt u ook contact opnemen met het Privacy Office van Air CRUD. </p><br>
                    <h2>8.3. Weigering of beperking van rechten</h2>
                    <p>Er kunnen zich situaties voordoen waarin wij uw hierboven in 8.2 beschreven rechten kunnen weigeren of beperken. Wij beoordelen per geval zorgvuldig of er sprake is van een dergelijke uitzondering. U ontvangt hiervan bericht. Zo kunnen wij uw verzoek tot inzage weigeren wanneer dit nodig is ter bescherming van de rechten en vrijheden van anderen, of we kunnen weigeren om uw persoonsgegevens te verwijderen als de verwerking van deze gegevens nodig is om aan wettelijke verplichtingen te voldoen. Het recht op gegevensoverdraagbaarheid geldt bijvoorbeeld niet als de persoonsgegevens niet door u zijn verstrekt of als we de gegevens niet verwerken op basis van uw toestemming of voor de uitvoering van een overeenkomst.</p><br>
                    <h2>8.4. Privacy Office</h2>
                    <p>Als u uw rechten wilt uitoefenen, kunt u dit doen door een verzoek in te dienen bij het Privacy Office van CRUDAirlines:</p><br>
                    <p> CRUDAirlines
                        Privacy Office - AMSPI
                        Postbus 7700
                        1117 ZL Luchthaven Schiphol
                        Nederland
                        E-mail: CRUDAirlinesPrivacyOffice@CRUDAirlines.com
                    </p><br>
                    <p>Als u uw rechten wilt uitoefenen met betrekking tot de verwerking van uw persoonsgegevens in het kader van CRUDbiz, kunt u ook contact opnemen met het Privacy Office van Air CRUD:</p><br>
                    <h2>8.5. Vragen, opmerkingen of klachten</h2>
                    <p>Heeft u vragen, opmerkingen of klachten over dit privacybeleid, neem dan gerust contact met ons op. Als uw probleem niet naar tevredenheid is opgelost, heeft u het recht om een klacht in te dienen bij de bevoegde toezichthouder.</p><br>
                </div>
            </div>
            <div class="privacybeleid_actualisatie_van_dit_privacybeleid">
                <button class="accordion">9. Actualisatie van dit privacybeleid</button>
                <div class="panel"><br>
                    <p>9.1. Dit privacybeleid treedt in werking op 20 augustus 2020 en vervangt ons privacybeleid d.d. 20 september 2019. Dit privacybeleid wordt van tijd tot tijd herzien. Wij informeren u over eventuele wijzigingen voordat deze in werking treden.</p><br>
                </div>
            </div>
        </div>
    </div>
    <?php include("footer.php") ?>
    <!---main js doet het niet dus heb hier alleen een beetje javascript toegevoegd voor de accordion---->
    <script>
        var accordion = document.getElementsByClassName("accordion");
        var a;

        for (a = 0; a < accordion.length; a++) {
            accordion[a].addEventListener("click", function() {
                this.classList.toggle("active");
                var panel = this.nextElementSibling;
                if (panel.style.maxHeight) {
                    panel.style.maxHeight = null;
                } else {
                    panel.style.maxHeight = panel.scrollHeight + "px";
                }
            });
        }
    </script>
    <script src="https://kit.fontawesome.com/33689bd479.js" crossorigin="anonymous"></script>
</body>

</html>